import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import CustomSidebar from "@/components/custom/custom-sidebar";
import CustomHeaderWrapper from "@/components/custom/custom-header-wrapper";

const InterSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${InterSans.variable} h-full antialiased dark`}>
      <body>
        <SidebarProvider>
          <CustomSidebar />
          <div className="flex flex-col h-screen w-full overflow-hidden">
            <CustomHeaderWrapper />
            <main className="flex-1 overflow-y-auto">{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
